"""initial revision

Revision ID: e1da2ea0086f
Revises: 
Create Date: 2023-05-13 12:18:07.552386

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e1da2ea0086f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slack_alias", sa.String(), nullable=True),
        sa.Column("oauth_access_token", sa.String(length=40), nullable=True),
        sa.Column("oauth_refresh_token", sa.String(length=40), nullable=True),
        sa.Column("oauth_userid", sa.String(length=40), nullable=True),
        sa.Column("oauth_expiration_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_slack_alias"), "users", ["slack_alias"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_slack_alias"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
