"""add-fitbit

Revision ID: 3ad50ca40a1e
Revises: 897c349bb45f
Create Date: 2023-05-14 00:25:50.540674

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3ad50ca40a1e"
down_revision = "897c349bb45f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fitbit_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("oauth_access_token", sa.String(length=40), nullable=True),
        sa.Column("oauth_refresh_token", sa.String(length=40), nullable=True),
        sa.Column("oauth_userid", sa.String(length=40), nullable=False),
        sa.Column("oauth_expiration_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    with op.batch_alter_table("fitbit_users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_fitbit_users_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fitbit_users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fitbit_users_id"))

    op.drop_table("fitbit_users")
    # ### end Alembic commands ###
