"""add-fitbit-last-sleep

Revision ID: de8be1ac65a5
Revises: d70a420a9a98
Create Date: 2023-06-17 17:29:45.100338

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "de8be1ac65a5"
down_revision = "d70a420a9a98"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fitbit_users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_sleep_start_time", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("last_sleep_end_time", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("last_sleep_sleep_minutes", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("last_sleep_wake_minutes", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fitbit_users", schema=None) as batch_op:
        batch_op.drop_column("last_sleep_wake_minutes")
        batch_op.drop_column("last_sleep_sleep_minutes")
        batch_op.drop_column("last_sleep_end_time")
        batch_op.drop_column("last_sleep_start_time")

    # ### end Alembic commands ###
