"""remove-fitbit_user-last_activity_log

Revision ID: 8e2961411310
Revises: 52f924fa8700
Create Date: 2023-08-14 19:37:03.465994

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8e2961411310"
down_revision = "52f924fa8700"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fitbit_users") as batch_op:
        batch_op.drop_column("last_activity_log_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fitbit_users", sa.Column("last_activity_log_id", sa.INTEGER(), nullable=True)
    )
    # ### end Alembic commands ###
