"""rename out of range to out of zone

Revision ID: ae34520a342d
Revises: faeda61f7f56
Create Date: 2024-09-06 10:52:58.775912

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "ae34520a342d"
down_revision = "faeda61f7f56"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE fitbit_activities RENAME COLUMN out_of_range_minutes TO out_of_zone_minutes;
        """
    )
    op.execute(
        """
        DROP VIEW fitbit_daily_activities;
        """
    )
    op.execute(
        """
        CREATE VIEW fitbit_daily_activities AS
            SELECT
                fitbit_user_id,
                type_id,
                date(updated_at) as date,
                count(*) as count_activities,
                sum(calories) as sum_calories,
                sum(distance_km) as sum_distance_km,
                sum(total_minutes) as sum_total_minutes,
                sum(fat_burn_minutes) as sum_fat_burn_minutes,
                sum(cardio_minutes) as sum_cardio_minutes,
                sum(peak_minutes) as sum_peak_minutes,
                sum(out_of_zone_minutes) as sum_out_of_zone_minutes
            FROM
                fitbit_activities
            GROUP BY
                fitbit_user_id,
                type_id,
                date(updated_at)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE fitbit_activities RENAME COLUMN out_of_zone_minutes TO out_of_range_minutes;
        """
    )
    op.execute(
        """
        DROP VIEW fitbit_daily_activities;
        """
    )
    op.execute(
        """
        CREATE VIEW fitbit_daily_activities AS
            SELECT
                fitbit_user_id,
                type_id,
                date(updated_at) as date,
                count(*) as count_activities,
                sum(calories) as sum_calories,
                sum(distance_km) as sum_distance_km,
                sum(total_minutes) as sum_total_minutes,
                sum(fat_burn_minutes) as sum_fat_burn_minutes,
                sum(cardio_minutes) as sum_cardio_minutes,
                sum(peak_minutes) as sum_peak_minutes,
                sum(out_of_range_minutes) as sum_out_of_range_minutes
            FROM
                fitbit_activities
            GROUP BY
                fitbit_user_id,
                type_id,
                date(updated_at)
        """
    )
    # ### end Alembic commands ###
