"""Added fitbit activity table

Revision ID: 77dca2f35afa
Revises: 8e2961411310
Create Date: 2024-01-21 16:16:57.440988

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "77dca2f35afa"
down_revision = "8e2961411310"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fitbit_activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("log_id", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("total_minutes", sa.Integer(), nullable=False),
        sa.Column("calories", sa.Integer(), nullable=False),
        sa.Column("fat_burn_minutes", sa.Integer(), nullable=True),
        sa.Column("cardio_minutes", sa.Integer(), nullable=True),
        sa.Column("peak_minutes", sa.Integer(), nullable=True),
        sa.Column("out_of_range_minutes", sa.Integer(), nullable=True),
        sa.Column("fitbit_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fitbit_user_id"], ["fitbit_users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("log_id"),
    )
    with op.batch_alter_table("fitbit_activities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fitbit_activities_id"), ["id"], unique=False
        )

    # ### end Alembic commands ###
    op.execute(
        """
        INSERT INTO fitbit_activities 
            (log_id, type_id, total_minutes, calories, fat_burn_minutes, cardio_minutes, peak_minutes, out_of_range_minutes, fitbit_user_id, created_at, updated_at)
        SELECT 
            log_id, type_id, total_minutes, calories, fat_burn_minutes, cardio_minutes, peak_minutes, out_of_range_minutes, fitbit_user_id, created_at, updated_at
        FROM
            fitbit_latest_activities

    """
    )
    op.drop_table("fitbit_latest_activities")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fitbit_activities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fitbit_activities_id"))

    op.drop_table("fitbit_activities")
    # ### end Alembic commands ###
